SET SERVEROUTPUT ON;
DECLARE
    PLS_INTEGER NUMBER;
BEGIN
    PLS_INTEGER:=1;
    WHILE (PLS_INTEGER<=5) LOOP
        DBMS_OUTPUT.PUT_LINE('El contador es: '|| PLS_INTEGER);
        PLS_INTEGER:=PLS_INTEGER+1;
    END LOOP;    
END;